### ISSUE TITLE
matterircd changes topic on connect

### ISSUE THREAD

**Issue by hloeung** [42wim/matterircd#282]
Hi,

I run an IRC proxy / bouncer. On connecting with another IRC client, it seems topics for most, if not all, channels I'm in are updated.  I think this might be related to commit c1f0356b3fb5e5eaa61de3ea0ea6298298f742dc

**Comment by hloeung** [comment]
At least it's shown in the IRC client, but not actually being done via the mattermost web UI.

**Comment by 42wim** [comment]
should be fixed in master, be sure to read changelog

**Comment by guilhermepiccoli** [comment]
Still happens to me, running matterircd on commit 9bfde7cd92757
