### ISSUE TITLE
backlog replay with incorrect username

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#316]
using matterircd 0.20, on mattermost:

When replaying the backlog, right after reconnecting I've noticed that the nickname that says the backlog is wrong

We currently have a channel where a bot is saying a lot (and is the only user really speaking in the channel).  When reconncting a random user is saying the stuff the bot said instead of the correct bot-nickname

**Comment by 42wim** [comment]
Need debug log for this, can you provide?

**Comment by 42wim** [comment]
This is possibly fixed with #326 
could you try master?

**Comment by Peter4825** [comment]
#326 does not fix this. Note that #326 is a fix for slack, this is a mattermost issue.

don't forget to talk to me on irc so we can get the logs sorted out :)
