### ISSUE TITLE
segmentation fault while using MMAUTHTOKEN authentication

### ISSUE THREAD

**Issue by jaroslawp** [42wim/matterircd#77]
While running:
```
matterircd-linux64 -debug --mmserver mattermost.company.domain
```
matterircd segfaults on login after trying to authenticate with MMAUTHTOKEN:
```
/msg mattermost login my-team jpolok MMAUTHTOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxx
```
llog/trace:
```
time="2016-12-03T16:15:20+01:00" level=info msg="enabling debug" module=matterircd 
time="2016-12-03T16:15:20+01:00" level=info msg="Listening on 127.0.0.1:6667" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=info msg="New connection: 127.0.0.1:58968" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="<- CAP LS" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="<- NICK jpolok" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="<- USER Thunderbird 0 * jpolok" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 001 jpolok :Welcome! jpolok!Thunderbird@localhost" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 002 jpolok :Your host is matterircd, running version 0.11.0" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 003 jpolok :This server was created Sat Dec  3 16:15:30 CET 2016" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 004 jpolok :matterircd 0.11.0 o o" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 251 jpolok :There are 2 users and 0 services on 1 servers" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 375 jpolok :- matterircd Message of the Day -" module=matterircd 
time="2016-12-03T16:15:30+01:00" level=debug msg="-> :matterircd 376 jpolok :End of /MOTD command." module=matterircd 
time="2016-12-03T16:15:49+01:00" level=debug msg="<- PRIVMSG mattermost :login my-team jpolok MMAUTHTOKEN=***************************" module=matterircd 
time="2016-12-03T16:15:49+01:00" level=info msg="login as jpolok (team: my-team) on mattermost.company.domain" module=matterircd 
time="2016-12-03T16:15:49+01:00" level=debug msg="trying login my-team jpolok mattermost.company.domain" module=matterclient 
time="2016-12-03T16:15:49+01:00" level=debug msg="trying login with MMAUTHTOKEN" module=matterclient 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6166f8]

goroutine 19 [running]:
panic(0x7f6560, 0xc420010140)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc420158360, 0x0, 0x0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:625 +0x1e8
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc420158360, 0x865c05, 0x1c)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:148 +0xa1e
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost(0xc42001a4d0, 0x7ffd11274118, 0x16, 0x1)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:55 +0x23f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc42001a4d0, 0xc42001a580, 0xc42014c6a4, 0x3a)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:83 +0xbd0
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdPrivMsg
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:294 +0x982
```
this happens with 0.11, 0.10.2 seems OK.

**Comment by clark42** [comment]
Hello !

I have a simillar issue but it's when I try to JOIN a chan from IRC :

`
DEBU[2016-12-07T09:36:09Z] <- JOIN #mkt                                  module=matterircd
DEBU[2016-12-07T09:36:09Z] Joining cq65cj5b5tb89n38wqfzy5ei7c            module=matterclient
DEBU[2016-12-07T09:36:09Z] WsReceiver: model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc4202ed2c0), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2016-12-07T09:36:09Z] WsReceiver: &model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc4202ed2c0), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2016-12-07T09:36:09Z] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"mkt", "channel_type":"O", "post":"{\"id\":\"id311feh6prydb4xr5kigckegr\",\"create_at\":1481103369737,\"update_at\":1481103369737,\"delete_at\":0,\"user_id\":\"t9a9dorw37frfjby5j84f7xopo\",\"channel_id\":\"cq65cj5b5tb89n38wqfzy5ei7c\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"jey has joined the channel.\",\"type\":\"system_join_leave\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"System", "team_id":"fazbb347sigpfbxum5qm4zcygo"}, Broadcast:(*model.WebsocketBroadcast)(0xc420256a40), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2016-12-07T09:36:09Z] adding admin to #mkt                          module=matterircd
DEBU[2016-12-07T09:36:09Z] syncMMChannel adding myself to mkt (id: cq65cj5b5tb89n38wqfzy5ei7c)  module=matterircd
DEBU[2016-12-07T09:36:09Z] -> :clark!clark@192.168.135.50 JOIN #mkt      module=matterircd
DEBU[2016-12-07T09:36:09Z] -> :matterircd 353 clark = #mkt :@admin clark   module=matterircd
DEBU[2016-12-07T09:36:09Z] -> :matterircd 366 clark #mkt :End of /NAMES list.  module=matterircd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 55 [running]:
panic(0x7f6560, 0xc420010080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4200c4370, 0x0, 0xc4204ede70)
        /data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:80 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4200c4370, 0x0, 0xc420314310, 0x4, 0xc420311ea0, 0x1a)
        /data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:98 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4200c4370, 0xc4202ed280)
        /data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:273 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200c4370)
        /data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:168 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
        /data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x42e
`

**Comment by 42wim** [comment]
@jaroslawp 0.11 only works with mattermost 3.5.x are you on that version?

**Comment by 42wim** [comment]
@clark42 mattermost and matterircd version ?

**Comment by jaroslawp** [comment]
@42wim, OK, that explains it: we are still on MM 3.4 ...thanks !

**Comment by clark42** [comment]
@42wim I'm using mattermost 3.5.1 and matterircd 0.11 (from source)

**Comment by 42wim** [comment]
@clark42 could you try building matterircd from current, your issue could be related to mattermost installations > 5000 users (eg framateam)

**Comment by dalhorinek** [comment]
I have the same problem authenticating with the password with the current version 0.11.1-dev

`
DEBU[2016-12-28T12:27:36+01:00] <- PRIVMSG mattermost :login dalhorinek ---password---  module=matterircd
INFO[2016-12-28T12:27:36+01:00] login as dalhorinek (team: workteam) on theserver  module=matterircd
DEBU[2016-12-28T12:27:36+01:00] trying login work dalhorinek theserver  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x222798]

goroutine 9 [running]:
panic(0x3f7c60, 0xc420010160)
        /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc4200895f0, 0x0, 0x0)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:625 +0x1e8
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc4200895f0, 0x46734d, 0x1c)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:148 +0xa1e
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost(0xc4200c0420, 0x7fff5fbff3b2, 0x19, 0x1)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:56 +0x23f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc4200c0420, 0xc4200c04d0, 0xc420017ad4, 0x20)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:83 +0xbd0
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdPrivMsg
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:294 +0x982
`

**Comment by clark42** [comment]
Hi @42wim 

Happy new year and thanks a lot again for all your works!

I've just try with the v011-dev (master branch)
```
$ ./matterircd --version
Version: 0.11.1-dev
```
and 3.5.1 mattermost version :
```
Version: 3.5.0
Build Number: 3.5.1
Build Date: Wed Nov 23 19:43:58 UTC 2016
Build Hash: 36f62c9e82350f58c902f64a5d3304872431ad41
Build Enterprise Ready: false
DB Version: 3.5.0
```
to join the a channel, and I still have the segfault issue :

Auth part :
```
DEBU[2017-01-02T12:12:22Z] <- PRIVMSG mattermost :login nbs-staff clark MMAUTHTOKEN=**************************  module=matterircd
INFO[2017-01-02T12:12:22Z] login as clark (team: nbs-staff) on mattermost.nbs-system.com  module=matterircd
DEBU[2017-01-02T12:12:22Z] trying login nbs-staff clark mattermost.nbs-system.com  module=matterclient
DEBU[2017-01-02T12:12:22Z] trying login with MMAUTHTOKEN                 module=matterclient
DEBU[2017-01-02T12:12:22Z] initUser(): found our team nbs-staff (id: fazbb347sigpfbxum5qm4zcygo)  module=matterclient
DEBU[2017-01-02T12:12:22Z] WsClient: making connection                   module=matterclient
INFO[2017-01-02T12:12:22Z] login succeeded                               module=matterircd
DEBU[2017-01-02T12:12:22Z] in addUsersToChannels()                       module=matterircd
```

Join part :
```
DEBU[2017-01-02T12:12:50Z] <- JOIN #alerts                               module=matterircd
DEBU[2017-01-02T12:12:50Z] Joining igp5apyqu7g9mddic7usjujzmo            module=matterclient
DEBU[2017-01-02T12:12:50Z] WsReceiver: model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42030f880), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:12:50Z] WsReceiver: &model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"t9a9dorw37frfjby5j84f7xopo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42030f880), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-01-02T12:12:50Z] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"sender_name":"System", "team_id":"fazbb347sigpfbxum5qm4zcygo", "channel_display_name":"alerts", "channel_type":"O", "post":"{\"id\":\"z7d6sreqhbfizc86n513b4rjtc\",\"create_at\":1483359170954,\"update_at\":1483359170954,\"delete_at\":0,\"user_id\":\"t9a9dorw37frfjby5j84f7xopo\",\"channel_id\":\"igp5apyqu7g9mddic7usjujzmo\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"jey has joined the channel.\",\"type\":\"system_join_leave\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}"}, Broadcast:(*model.WebsocketBroadcast)(0xc42026c440), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:12:50Z] adding admin to #alerts                       module=matterircd
DEBU[2017-01-02T12:12:50Z] syncMMChannel adding myself to alerts (id: igp5apyqu7g9mddic7usjujzmo)  module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :clark!clark@192.168.135.50 JOIN #alerts   module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :matterircd 353 clark = #alerts :@admin clark   module=matterircd
DEBU[2017-01-02T12:12:50Z] -> :matterircd 366 clark #alerts :End of /NAMES list.  module=matterircd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 44 [running]:
panic(0x7f6560, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4200b4420, 0x0, 0xc4204b7e70)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:81 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4200b4420, 0x0, 0xc4203450b0, 0x7, 0xc420331f40, 0x1a)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:99 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4200b4420, 0xc42030f840)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:278 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200b4420)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:169 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:65 +0x42e
```

I've just try with another user (not a gitlab user but a standard one).. and I have the same issue :(

Auth part :
```
DEBU[2017-01-02T12:19:54Z] <- PRIVMSG mattermost :login nbs-staff inglip 3dTi8uwPhQMNXFcRsKtH  module=matterircd
INFO[2017-01-02T12:19:54Z] login as inglip (team: nbs-staff) on mattermost.nbs-system.com  module=matterircd
DEBU[2017-01-02T12:19:54Z] trying login nbs-staff inglip mattermost.nbs-system.com  module=matterclient
DEBU[2017-01-02T12:19:55Z] <- PING 10.1.170.1                            module=matterircd
DEBU[2017-01-02T12:19:55Z] -> :matterircd PONG matterircd :10.1.170.1    module=matterircd
DEBU[2017-01-02T12:19:55Z] initUser(): found our team nbs-staff (id: fazbb347sigpfbxum5qm4zcygo)  module=matterclient
DEBU[2017-01-02T12:19:55Z] WsClient: making connection                   module=matterclient
INFO[2017-01-02T12:19:55Z] login succeeded                               module=matterircd
DEBU[2017-01-02T12:19:55Z] in addUsersToChannels()                       module=matterircd
```

Join part :
```
DEBU[2017-01-02T12:20:02Z] -> :matterircd 324 inglip #inglip :           module=matterircd
DEBU[2017-01-02T12:20:14Z] <- JOIN #com                                  module=matterircd
DEBU[2017-01-02T12:20:14Z] Joining f6gya59d938cxn4wertbc6nyze            module=matterclient
DEBU[2017-01-02T12:20:14Z] WsReceiver: model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"user_id":"a3mo7pzi4tgi5g87xnea8i39sw", "team_id":"fazbb347sigpfbxum5qm4zcygo"}, Broadcast:(*model.WebsocketBroadcast)(0xc420247500), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-02T12:20:14Z] WsReceiver: &model.WebSocketEvent{Event:"user_added", Data:map[string]interface {}{"team_id":"fazbb347sigpfbxum5qm4zcygo", "user_id":"a3mo7pzi4tgi5g87xnea8i39sw"}, Broadcast:(*model.WebsocketBroadcast)(0xc420247500), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-01-02T12:20:14Z] adding admin to #com                          module=matterircd
DEBU[2017-01-02T12:20:14Z] adding jey to #com                            module=matterircd
DEBU[2017-01-02T12:20:14Z] syncMMChannel adding myself to com (id: f6gya59d938cxn4wertbc6nyze)  module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :inglip!inglip@192.168.135.50 JOIN #com    module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :matterircd 353 inglip = #com :@admin inglip jey   module=matterircd
DEBU[2017-01-02T12:20:14Z] -> :matterircd 366 inglip #com :End of /NAMES list.  module=matterircd
DEBU[2017-01-02T12:20:14Z] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"com", "channel_type":"O", "post":"{\"id\":\"6aui48y1n3bcifzrc5ft7imgzo\",\"create_at\":1483359614888,\"update_at\":1483359614888,\"delete_at\":0,\"user_id\":\"a3mo7pzi4tgi5g87xnea8i39sw\",\"channel_id\":\"f6gya59d938cxn4wertbc6nyze\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"inglip has joined the channel.\",\"type\":\"system_join_leave\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"System", "team_id":"fazbb347sigpfbxum5qm4zcygo"}, Broadcast:(*model.WebsocketBroadcast)(0xc42040a680), PreComputeJson:[]uint8(nil)}  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 42 [running]:
panic(0x7f6560, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4200b4420, 0x0, 0xc420185e70)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:81 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4200b4420, 0x0, 0xc42032abb0, 0x4, 0xc4202e4ac0, 0x1a)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:99 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4200b4420, 0xc4202474c0)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:278 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200b4420)
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:169 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
	/data/go/work/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:65 +0x42e
```

It seems it's not a problem with the MMAUTHTOKEN (because I've the same segfault issue with a standard user).

Do you want I open another issue ?

Best regards

Clark

**Comment by der-tale** [comment]
I also experience the same panic every few hours:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4a15cd]

goroutine 616 [running]:
panic(0x7f6560, 0xc4200100a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).createMMUser(0xc4203fe160, 0x0, 0xc42046de70)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:80 +0x3d
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).addUserToChannel(0xc4203fe160, 0x0, 0xc4203a7620, 0x13, 0xc4202f40c0, 0x1a)  
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:98 +0x3c
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsActionUserAdded(0xc4203fe160, 0xc420380000)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:273 +0x14f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4203fe160)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:168 +0x29a
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x42e
```

**Comment by 42wim** [comment]
@clark42 thanks for the detailed report
I just released v0.11.1 which should fix everyones problem.

**Comment by clark42** [comment]
@42wim I've just test it, and for the join issue, it works perfectly now ;)
thanks you !

**Comment by dalhorinek** [comment]
@42wim Thanks for new release, but for my case, authentication still fails on segmentation fault. 

Is it related?
```
DEBU[2017-01-05T20:37:07+01:00] trying login company username mattermost.company.domain  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2229a8]

goroutine 9 [running]:
panic(0x3f7e60, 0xc420010170)
        /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc4200915f0, 0x0, 0x0)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:625 +0x1e8
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc4200915f0, 0x467551, 0x1c)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:148 +0xa1e
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost(0xc4200c8370, 0x7fff5fbff39f, 0x19, 0x1)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:56 +0x23f
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc4200c8370, 0xc4200c8420, 0xc4200179d4, 0x20)
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:83 +0xbd0
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdPrivMsg
        /Users/dal/local/share/matterircd/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:294 +0x982
```

**Comment by 42wim** [comment]
@dalhorinek Seems like you are not using MMAUTHTOKEN ? just login/password ?
What version is your mattermost setup ?
